# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's



# name or the intended use of these models
name: 'dbt_for_elt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_for_elt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_for_elt:
    clean_data:
      +materialized: table

    # +materialized: view
    # +schema: dbt_for_elt
    # +database: dbt_for_elt
    # +enabled: true
  # my_project:
  #   example:
  #     materialized: view  # Example configuration
