version: 2

sources:
  - name: staging
    database: my_project
    schema: public
    tables:
      - name: /home/nahomnadew/Desktop/10x/week7/Kara_Solutions/data/cleaned_telegram_data.csv
        description: "Raw data scraped from Telegram channels"
        columns:
          - name: channel_title
            description: "Titile of telegram channels"
          - name: channel_username
            description: "Unique username for each channel"
          - name: message_id
            description: "unique ID for each messages"
          - name: message
            description: "contents in the message"
          - name: message_date
            description: "datetime for the messages put"
          - name: media_path
            description: "if any media in the messages"
          - name: emoji_used
            description: "emojis if any and 'no emoji' if the isny any"
          - name: youtube_links
            description: "links if any of youtube, 'no link' is there isnt any"

model:
  - name: clean_data
    description: "Cleaned data from telegram channels"
         columns:
          - name: channel_title
            description: "Titile of telegram channels"
          - name: channel_username
            description: "Unique username for each channel"
          - name: message_id
            description: "unique ID for each messages"
          - name: message
            description: "contents in the message"
          - name: message_date
            description: "datetime for the messages put"
          - name: media_path
            description: "if any media in the messages"
          - name: emoji_used
            description: "emojis if any and 'no emoji' if the isny any"
          - name: youtube_links
            description: "links if any of youtube, 'no link' is there isnt any"
